name: jb_course
channels:
  - conda-forge
dependencies:
  - jupyter-book

  # Diagrams with Mermaid.js
  - sphinxcontrib-mermaid

  - pip
  - pip:
    - sphinx-proof
    - git+https://github.com/QuantEcon/quantecon-book-theme.git
